[build]
  publish = "public"  # The directory to publish
  command = "npm run build"  # Your build command, if you have one. If not, you can leave this out.

[[redirects]]
  from = "/*"
  to = "/html/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/html/login.html"
  status = 200
   
[[redirects]]
  from = "/signup"
  to = "/html/signup.html"
  status = 200
   
[[redirects]]
  from = "/about"
  to = "/html/about.html"
  status = 200
   
[[redirects]]
  from = "/help"
  to = "/html/help.html"
  status = 200
   
[[redirects]]
  from = "/platform"
  to = "/html/wasteradict.html"
  status = 200
   
[[redirects]]
  from = "/notifaications"
  to = "/html/notifaications.html"
  status = 200
   